### ISSUE TITLE
don't work with openfl

### ISSUE THREAD

**Issue by R3D9477** [hamaluik/haxe-partials#2]
Hi. Is it possible to work with openfl ?

for example

Main.hx:

```
import openfl.display.Sprite;
import partials.Partial;

@:partials(PartialFoo, PartialBar)
class Main extends Sprite implements Partial {
    public function new () {
        super ();

        foo();
        bar();
    }
}
```

PartialBar.hx:

```
class PartialBar implements partials.Partial {
    public static function bar() {
        trace("BAR!");
    }
}
```

PartialFoo.hx

```
class PartialFoo implements partials.Partial {
    public static function foo() {
        trace("FOO!");
    }
}
```

compilation was succeed, but compiled application fails with 

```
Called from ? line 1
Uncaught exception - Invalid field access : main
```

Thanks.

**Comment by francescoagati** [comment]
you don't create main method in your code?

**Comment by R3D9477** [comment]
No, I don't creating this method manually.
This method will be created by OpenFL at compilation-time in class ApplicationMain.

**Comment by francescoagati** [comment]
maybe there is a conflict with openfl?
try to apply partials to an extended class and after extend Main with an extended class

@:partials(PartialFoo, PartialBar)
class _Main extends Sprite implements Partial {


class Main extends _Main {
